Enhancement jl1
sadohert/mattermost-cse-python-tools pull request #1
Opened 2023-09-21 14:13 UTC by jlandells

Updated code to add some flexibility with connections and parameters.

Add README

2023-09-21 15:55 UTC, sadohert requested changes
Just a few minor things I noted, but otherwise lgtm... thanks for adding this @jlandells !

2023-09-21 15:55 UTC, sadohert commented on README.md
> +All of these scripts will require Python, as well as the [mattermostdriver](https://vaelor.github.io/python-mattermost-driver/index.html) package.  This package can  typically be added to your enviro
Would this be:

> through the user via

?

2023-09-21 15:55 UTC, sadohert commented on README.md
> +`--team TEAM` | TheThe name of the team to query. Use the url-friendly version, not the Team Display Name. If omitted, defaults to all users.
> TheThe

2023-10-23 10:53 UTC, jlandells commented on README.md
> +All of these scripts will require Python, as well as the [mattermostdriver](https://vaelor.github.io/python-mattermost-driver/index.html) package.  This package can  typically be added to your enviro
Fixed!

2023-10-23 10:53 UTC, jlandells commented on README.md
> +`--team TEAM` | TheThe name of the team to query. Use the url-friendly version, not the Team Display Name. If omitted, defaults to all users.
Fixed!

2023-10-23 10:54 UTC, jlandells commented
Changes have been pushed.  Should be ready to merge now.

2023-10-24 15:09 UTC, sadohert commented
LGTM.  Thanks John!

2023-10-24 15:09 UTC, merged